language: java
# Attempt to resolve most dependencies without actually compiling
# See http://docs.travis-ci.com/user/languages/java/#Dependency-Management
install: travis_wait mvn dependency:resolve
script: mvn --batch-mode --settings settings.xml test -Dgwt.validateOnly -Darquillian.jboss.home=/dev/null -DstaticAnalysis
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8

matrix:
  fast_finish: true
